import pandas as pd

rename_evac = {'q1kat':'evac',
               's2':'evac_notice',
               's3':'manda_or_volun',
               's4_1':'heard_notice_radio_tv',
               's4_2':'heard_notice_mouth',
               's4_3':'police_loudspeaker',
               's4_4':'police_doortodoor',
               's4_5':'authority_phonecall',
               's4_6':'newspaper',
               's4_7':'NOAA_weather_radio',
               's4_8':'other',
               's4_9':'do not know',
               's4_10':'what?',
               's5':'notice_early_enough',
               's6':'notice_clear',
               's7':'know_evac_zone',
               's7b':'in_evac_zone',
               's9':'need_to_work',
               's10_1':'work_affect_notatall',
               's10_2':'work_affect_stopped_househd',
               's10_3':'work_affect_stopped_part_househd',
               's10_4':'work_affect_delayed',
               's10_5':'work_affect_other',
               's10_6':'work_affect_donotknow',
               's10_7':'work_affect_what?',
               's11':'have_children_at_school',
               's12':'school_closed_early_enough',
               'fcat1':'evac_cat1',
               's25':'window_protect',
               's26_1':'protect_permanent_metal_panel',
               's26_2':'protect_removable_metal_panel',
               's26_3':'protect_plywood_sheet',
               's26_4':'protect_security_film',
               's26_5':'protect_resistent_glass',
               's26_6':"protect_other",
               's26_7':"protect_donotknow",
               's26_8':'protect_what?',
               's29':'protect_before_katrina',
               's30':'permanent_or_katrina',
               's31':'protect_affect_evac',
               's35':'lost_job_katrina',
               's37':'plan_to_move',
               's38':'own_business',
               's39':'plan_to_move_business',
               's41':'home_damaged',
               's42':'damage_amount',
               's42a':'cost_of_damage',
               's42b':'home_situation',
               'q15':'continue',
               'ratef_1':'importance_hit_forecast',
               'ratef_3':'importance_traffic',
               'ratef_4':'importance_time_before_hit',
               'ratef_5':'importance_evac_order',
               'ratef_6':'importance_protect_home',
               'ratef_7':'importance_flood',
               'ratef_8':'importance_return_home',
               'ratef_9':'importance_protect_from_crime',
               'ratef_10':'importance_keep_family_together',
               'ratef_11':'importance_job_requirements',
               'ratef_12':'importance_medical_needs',
               'ratef_13':'importance_pets',
               'ratef_1':'most_important_hit_forecast',
               'ratef_3':'most_important_traffic',
               'ratef_4':'most_important_time_before_hit',
               'ratef_5':'most_important_evac_order',
               'ratef_6':'most_important_protect_home',
               'ratef_7':'most_important_flood',
               'ratef_8':'most_important_return_home',
               'ratef_9':'most_important_protect_from_crime',
               'ratef_10':'most_important_keep_family_together',
               'ratef_11':'most_important_job_requirements',
               'ratef_12':'most_important_medical_needs',
               'ratef_13':'most_important_pets',
               
           
               

               }

df = pd.read_csv('IvanKat.csv')